import {
  Home,
  Monitor,
  FileText,
  Download,
  Image as ImageIcon,
  HardDrive,
  Folder,
  File,
  Search,
  ChevronLeft,
  ChevronRight,
  List as ListIcon,
  Settings as SettingsIcon,
  Grid,
  FolderPlus,
  FilePlus,
  Clipboard,
  ExternalLink,
  Terminal,
  Copy,
  CopyPlus,
  Pencil,
  Package,
  Trash,
  Info,
  FileCode,
  FileVideo,
  FileAudio,
  FileArchive,
  FileDigit,
  FileSearch,
} from "lucide-solid";
import { Dynamic } from "solid-js/web";

// Utility macro to quickly build standard components to avoid writing it 100 times
const iCmp = (iconID: string) => (props: any) => (
  <iconify-icon
    icon={iconID}
    width={props.size}
    height={props.size}
    {...props}
  ></iconify-icon>
);

export const IconMap: Record<string, Record<string, any>> = {
  lucide: {
    Home,
    Monitor,
    FileText,
    Download,
    Image: ImageIcon,
    HardDrive,
    Folder,
    File,
    Search,
    ChevronLeft,
    ChevronRight,
    List: ListIcon,
    Grid: Grid,
    Settings: SettingsIcon,
    FolderPlus,
    FilePlus,
    Clipboard,
    ExternalLink,
    Terminal,
    Copy,
    CopyPlus,
    Pencil,
    Package,
    Trash,
    Info,
    FileCode,
    FileVideo,
    FileAudio,
    FileArchive,
    FileDigit,
    FileSearch,
  },
  material: {
    Home: iCmp("mdi:home"),
    Monitor: iCmp("mdi:monitor"),
    FileText: iCmp("mdi:file-document"),
    Download: iCmp("mdi:download"),
    Image: iCmp("mdi:image"),
    HardDrive: iCmp("mdi:harddisk"),
    Folder: iCmp("mdi:folder"),
    File: iCmp("mdi:file"),
    Search: iCmp("mdi:magnify"),
    ChevronLeft: iCmp("mdi:chevron-left"),
    ChevronRight: iCmp("mdi:chevron-right"),
    List: iCmp("mdi:format-list-bulleted"),
    Grid: iCmp("mdi:view-grid"),
    Settings: iCmp("mdi:cog"),
    FolderPlus: iCmp("mdi:folder-plus"),
    FilePlus: iCmp("mdi:file-plus"),
    Clipboard: iCmp("mdi:clipboard-outline"),
    ExternalLink: iCmp("mdi:open-in-new"),
    Terminal: iCmp("mdi:terminal"),
    Copy: iCmp("mdi:content-copy"),
    CopyPlus: iCmp("mdi:content-duplicate"),
    Pencil: iCmp("mdi:pencil"),
    Package: iCmp("mdi:package-variant-closed"),
    Trash: iCmp("mdi:trash-can"),
    Info: iCmp("mdi:information"),
    FileCode: iCmp("mdi:file-code"),
    FileVideo: iCmp("mdi:file-video"),
    FileAudio: iCmp("mdi:file-music"),
    FileArchive: iCmp("mdi:file-cabinet"),
    FileDigit: iCmp("mdi:file-numeric"),
    FileSearch: iCmp("mdi:file-search"),
  },
  catppuccin: {
    Home: iCmp("lucide:home"),
    Monitor: iCmp("lucide:monitor"),
    FileText: iCmp("catppuccin:file"),
    Download: iCmp("catppuccin:folder-download"),
    Image: iCmp("catppuccin:image"),
    HardDrive: iCmp("lucide:hard-drive"),
    Folder: iCmp("catppuccin:folder"),
    File: iCmp("catppuccin:file"),
    Search: iCmp("lucide:search"),
    ChevronLeft: iCmp("lucide:chevron-left"),
    ChevronRight: iCmp("lucide:chevron-right"),
    List: iCmp("lucide:list"),
    Grid: iCmp("lucide:grid"),
    Settings: iCmp("lucide:settings"),
    FolderPlus: iCmp("lucide:folder-plus"),
    FilePlus: iCmp("lucide:file-plus"),
    Clipboard: iCmp("lucide:clipboard"),
    ExternalLink: iCmp("lucide:external-link"),
    Terminal: iCmp("lucide:terminal"),
    Copy: iCmp("lucide:copy"),
    CopyPlus: iCmp("lucide:copy-plus"),
    Pencil: iCmp("lucide:pencil"),
    Package: iCmp("lucide:package"),
    Trash: iCmp("lucide:trash"),
    Info: iCmp("lucide:info"),
    FileCode: iCmp("catppuccin:javascript"),
    FileVideo: iCmp("catppuccin:video"),
    FileAudio: iCmp("catppuccin:audio"),
    FileArchive: iCmp("catppuccin:zip"),
    FileDigit: iCmp("catppuccin:binary"),
    FileSearch: iCmp("lucide:file-search"),
  },
  fontawesome: {
    Home: iCmp("fa6-solid:house"),
    Monitor: iCmp("fa6-solid:desktop"),
    FileText: iCmp("fa6-solid:file-lines"),
    Download: iCmp("fa6-solid:download"),
    Image: iCmp("fa6-solid:image"),
    HardDrive: iCmp("fa6-solid:hard-drive"),
    Folder: iCmp("fa6-solid:folder"),
    File: iCmp("fa6-solid:file"),
    Search: iCmp("fa6-solid:magnifying-glass"),
    ChevronLeft: iCmp("fa6-solid:chevron-left"),
    ChevronRight: iCmp("fa6-solid:chevron-right"),
    List: iCmp("fa6-solid:list"),
    Grid: iCmp("fa6-solid:border-all"),
    Settings: iCmp("fa6-solid:gear"),
    FolderPlus: iCmp("fa6-solid:folder-plus"),
    FilePlus: iCmp("fa6-solid:file-circle-plus"),
    Clipboard: iCmp("fa6-solid:clipboard"),
    ExternalLink: iCmp("fa6-solid:up-right-from-square"),
    Terminal: iCmp("fa6-solid:terminal"),
    Copy: iCmp("fa6-solid:copy"),
    CopyPlus: iCmp("fa6-solid:clone"),
    Pencil: iCmp("fa6-solid:pencil"),
    Package: iCmp("fa6-solid:box-archive"),
    Trash: iCmp("fa6-solid:trash-can"),
    Info: iCmp("fa6-solid:circle-info"),
    FileCode: iCmp("fa6-solid:file-code"),
    FileVideo: iCmp("fa6-solid:file-video"),
    FileAudio: iCmp("fa6-solid:file-audio"),
    FileArchive: iCmp("fa6-solid:file-zipper"),
    FileDigit: iCmp("fa6-solid:file-excel"),
    FileSearch: iCmp("fa6-solid:file-magnifying-glass"),
  },
  heroicons: {
    Home: iCmp("heroicons:home-solid"),
    Monitor: iCmp("heroicons:computer-desktop-solid"),
    FileText: iCmp("heroicons:document-text-solid"),
    Download: iCmp("heroicons:arrow-down-tray-solid"),
    Image: iCmp("heroicons:photo-solid"),
    HardDrive: iCmp("heroicons:server-solid"),
    Folder: iCmp("heroicons:folder-solid"),
    File: iCmp("heroicons:document-solid"),
    Search: iCmp("heroicons:magnifying-glass-solid"),
    ChevronLeft: iCmp("heroicons:chevron-left-solid"),
    ChevronRight: iCmp("heroicons:chevron-right-solid"),
    List: iCmp("heroicons:list-bullet-solid"),
    Grid: iCmp("heroicons:squares-2x2-solid"),
    Settings: iCmp("heroicons:cog-6-tooth-solid"),
    FolderPlus: iCmp("heroicons:folder-plus-solid"),
    FilePlus: iCmp("heroicons:document-plus-solid"),
    Clipboard: iCmp("heroicons:clipboard-solid"),
    ExternalLink: iCmp("heroicons:arrow-top-right-on-square-solid"),
    Terminal: iCmp("heroicons:command-line-solid"),
    Copy: iCmp("heroicons:document-duplicate-solid"),
    CopyPlus: iCmp("heroicons:plus-circle-solid"),
    Pencil: iCmp("heroicons:pencil-solid"),
    Package: iCmp("heroicons:archive-box-solid"),
    Trash: iCmp("heroicons:trash-solid"),
    Info: iCmp("heroicons:information-circle-solid"),
    FileCode: iCmp("heroicons:code-bracket-solid"),
    FileVideo: iCmp("heroicons:video-camera-solid"),
    FileAudio: iCmp("heroicons:musical-note-solid"),
    FileArchive: iCmp("heroicons:archive-box-arrow-down-solid"),
    FileDigit: iCmp("heroicons:calculator-solid"),
    FileSearch: iCmp("heroicons:document-magnifying-glass-solid"),
  },
  bootstrap: {
    Home: iCmp("bi:house-fill"),
    Monitor: iCmp("bi:display-fill"),
    FileText: iCmp("bi:file-earmark-text-fill"),
    Download: iCmp("bi:download"),
    Image: iCmp("bi:image-fill"),
    HardDrive: iCmp("bi:device-hdd-fill"),
    Folder: iCmp("bi:folder-fill"),
    File: iCmp("bi:file-earmark-fill"),
    Search: iCmp("bi:search"),
    ChevronLeft: iCmp("bi:chevron-left"),
    ChevronRight: iCmp("bi:chevron-right"),
    List: iCmp("bi:list-ul"),
    Grid: iCmp("bi:grid-1x2-fill"),
    Settings: iCmp("bi:gear-fill"),
    FolderPlus: iCmp("bi:folder-plus"),
    FilePlus: iCmp("bi:file-earmark-plus"),
    Clipboard: iCmp("bi:clipboard"),
    ExternalLink: iCmp("bi:box-arrow-up-right"),
    Terminal: iCmp("bi:terminal-fill"),
    Copy: iCmp("bi:copy"),
    CopyPlus: iCmp("bi:plus-square-fill"),
    Pencil: iCmp("bi:pencil-fill"),
    Package: iCmp("bi:archive-fill"),
    Trash: iCmp("bi:trash-fill"),
    Info: iCmp("bi:info-circle-fill"),
    FileCode: iCmp("bi:file-earmark-code-fill"),
    FileVideo: iCmp("bi:file-earmark-play-fill"),
    FileAudio: iCmp("bi:file-earmark-music-fill"),
    FileArchive: iCmp("bi:file-earmark-zip-fill"),
    FileDigit: iCmp("bi:file-earmark-binary-fill"),
    FileSearch: iCmp("bi:file-earmark-medical-fill"),
  },
  phosphor: {
    Home: iCmp("ph:house-fill"),
    Monitor: iCmp("ph:desktop-fill"),
    FileText: iCmp("ph:file-text-fill"),
    Download: iCmp("ph:download-simple-fill"),
    Image: iCmp("ph:image-fill"),
    HardDrive: iCmp("ph:hard-drive-fill"),
    Folder: iCmp("ph:folder-fill"),
    File: iCmp("ph:file-fill"),
    Search: iCmp("ph:magnifying-glass-bold"),
    ChevronLeft: iCmp("ph:caret-left-bold"),
    ChevronRight: iCmp("ph:caret-right-bold"),
    List: iCmp("ph:list-checks-fill"),
    Grid: iCmp("ph:squares-four-fill"),
    Settings: iCmp("ph:gear-fill"),
    FolderPlus: iCmp("ph:folder-plus-fill"),
    FilePlus: iCmp("ph:file-plus-fill"),
    Clipboard: iCmp("ph:clipboard-fill"),
    ExternalLink: iCmp("ph:arrow-square-out-fill"),
    Terminal: iCmp("ph:terminal-window-fill"),
    Copy: iCmp("ph:copy-fill"),
    CopyPlus: iCmp("ph:copy-simple-fill"),
    Pencil: iCmp("ph:pencil-simple-fill"),
    Package: iCmp("ph:archive-fill"),
    Trash: iCmp("ph:trash-fill"),
    Info: iCmp("ph:info-fill"),
    FileCode: iCmp("ph:file-code-fill"),
    FileVideo: iCmp("ph:file-video-fill"),
    FileAudio: iCmp("ph:file-audio-fill"),
    FileArchive: iCmp("ph:file-zip-fill"),
    FileDigit: iCmp("ph:file-lock-fill"),
    FileSearch: iCmp("ph:file-search-fill"),
  },
  tabler: {
    Home: iCmp("tabler:home-filled"),
    Monitor: iCmp("tabler:device-desktop"),
    FileText: iCmp("tabler:file-text"),
    Download: iCmp("tabler:download"),
    Image: iCmp("tabler:photo-filled"),
    HardDrive: iCmp("tabler:database"),
    Folder: iCmp("tabler:folder-filled"),
    File: iCmp("tabler:file-filled"),
    Search: iCmp("tabler:search"),
    ChevronLeft: iCmp("tabler:chevron-left"),
    ChevronRight: iCmp("tabler:chevron-right"),
    List: iCmp("tabler:list"),
    Grid: iCmp("tabler:layout-grid-filled"),
    Settings: iCmp("tabler:settings-filled"),
    FolderPlus: iCmp("tabler:folder-plus"),
    FilePlus: iCmp("tabler:file-plus"),
    Clipboard: iCmp("tabler:clipboard"),
    ExternalLink: iCmp("tabler:external-link"),
    Terminal: iCmp("tabler:terminal-2"),
    Copy: iCmp("tabler:copy"),
    CopyPlus: iCmp("tabler:copy-plus"),
    Pencil: iCmp("tabler:pencil"),
    Package: iCmp("tabler:package"),
    Trash: iCmp("tabler:trash"),
    Info: iCmp("tabler:info-circle"),
    FileCode: iCmp("tabler:file-code-2"),
    FileVideo: iCmp("tabler:file-movie"),
    FileAudio: iCmp("tabler:file-music"),
    FileArchive: iCmp("tabler:file-zip"),
    FileDigit: iCmp("tabler:file-spreadsheet"),
    FileSearch: iCmp("tabler:file-search"),
  },
};

export type IconPack = keyof typeof IconMap;

export function AppIcon(props: {
  name: string;
  pack: IconPack;
  size?: number;
  [key: string]: any;
}) {
  return (
    <Dynamic
      component={
        IconMap[props.pack]?.[props.name] ||
        IconMap[props.pack]?.["File"] ||
        (() => null)
      }
      {...props}
    />
  );
}
